name: Test
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: "pip"

      - name: Install package
        run: pip install .

      - name: Run
        shell: bash
        run: |
          mcservers --path ./servers.dat --export

      - name: Verify
        shell: bash
        run: |
          cat ./servers_*.txt